// Generated by installer.py — do not edit by hand for deploy.
window.APP_CONFIG = {
  apiJobsUrl: "https://trikmur3wk.execute-api.us-west-2.amazonaws.com/jobs",
  apiGatewayUrl: "https://trikmur3wk.execute-api.us-west-2.amazonaws.com/jobs",
  apiGatewayHealthUrl: "https://trikmur3wk.execute-api.us-west-2.amazonaws.com/health",
  apiDocumentsUrl: "https://trikmur3wk.execute-api.us-west-2.amazonaws.com/documents",
  projectName: "document-ai",
  companyName: "\ubb38\uc11c \ubd84\uc11d \uc194\ub8e8\uc158",
  cognitoUserPoolId: "us-west-2_OfjbWLWGa",
  cognitoClientId: "5aacpo88fg09ipbgh0nmpa4fl2",
  cognitoRegion: "us-west-2",
  essSharingUrl: "https://d3rip56yv3q50v.cloudfront.net",
};
